Update ompl_interface_tutorial.rst
moveit/moveit2_tutorials pull request #542
Opened 2022-11-07 15:17 UTC by ejalaa12

Update the tutorial to explain how to create a Custom Optimization Objective for OMPL as described in this pull request #1436 (https://github.com/ros-planning/moveit2/pull/1436)

2022-11-07 23:06 UTC, mamoll requested changes

2022-11-07 23:06 UTC, mamoll commented on doc/examples/ompl_interface/ompl_interface_tutorial.rst
> +#. In your own package, create your an optimization objective class for OMPL. For more information on the OMPL optimal planners, the reader is referred to the `OMPL - Optimal Planning documentation <
```suggestion
#. In your own package, create your own optimization objective class for OMPL. For more information on the OMPL optimal planners, the reader is referred to the `OMPL - Optimal Planning documentation <http://ompl.kavrakilab.org/optimalPlanning.html>`_.
```

2022-11-07 23:06 UTC, mamoll commented on doc/examples/ompl_interface/ompl_interface_tutorial.rst
> +#. In your .cpp file, include ``"moveit/ompl_interface/ompl_optimization_objective_loader.h"`` and add, at the end, the macro ``MOVEIT_OPTIMIZATION_OBJECTIVE_PLUGIN(namespace, class_name)``, with the
```suggestion
#. In your .cpp file, include ``"moveit/ompl_interface/ompl_optimization_objective_loader.h"`` and add, at the end, the macro ``MOVEIT_OPTIMIZATION_OBJECTIVE_PLUGIN(namespace, class_name)``, with the right namespace and class name you used.
```

2022-11-07 23:06 UTC, mamoll commented on doc/examples/ompl_interface/ompl_interface_tutorial.rst
> +    <class name="custom_optimizer"
```suggestion
    <class name="custom_objective"
```

2022-11-07 23:06 UTC, mamoll commented on doc/examples/ompl_interface/ompl_interface_tutorial.rst
> +   The ``bass_class`` is the fully qualified base class type for the plugin and does not need to be modified.
```suggestion
   The ``bass_class_type`` is the fully qualified base class type for the plugin and does not need to be modified.
```
Or change `base_class_type` in the XML snippet above to `base_class`?

2022-11-08 08:28 UTC, ejalaa12 commented
@mamoll Thanks for the review, just fixed all the typos :)

2022-11-28 14:51 UTC, stephanie-eng commented on doc/examples/ompl_interface/ompl_interface_tutorial.rst
> +   The ``bass_class_type`` is the fully qualified base class type for the plugin and does not need to be modified.
```suggestion
   The ``base_class_type`` is the fully qualified base class type for the plugin and does not need to be modified.
```

2023-05-05 10:31 UTC, ejalaa12 commented
@stephanie-eng Friendly ping :)

2024-11-23 19:24 UTC, sea-bass approved these changes
I'm not sure why this fell through, but I was scrolling and it looks good to me.

2024-11-23 19:25 UTC, merged

2024-11-23 19:28 UTC, stephanie-eng commented
I thought this is based on https://github.com/moveit/moveit2/pull/1436 which is not merged yet?

2024-11-23 19:30 UTC, sea-bass commented
Oh no. I did not realize it was documenting a new feature. I'll revert.

2024-11-23 19:33 UTC, sea-bass commented
Reverted in https://github.com/moveit/moveit2_tutorials/commit/513ce271d41fb9424543a67b689c70f497d37856

If this feature lands at some point, please feel free to open up a new pull request here.

Thanks @stephanie-eng!